maintainer       "Lamont Granquist"
maintainer_email "lamont@scriptkiddie.org"
license          "MIT"
name             "sk_s3_file"
description      "Pure Ruby Chef LWRP for pulling files from S3"
long_description "Pure Ruby Chef LWRP for pulling files from S3"
version          "2.0.6"
